### ISSUE TITLE
GregoBase site using outdated Gregorio?

### ISSUE THREAD

**Issue by cwrinn** [gregorio-project/GregoBase#12]
I notice that the output of Gloria XI does not include a quilisma in the final Patris, even though the notation is written in the markup.

When I copy the gabc locally and use gregorio 5.0.1 to render a pdf it includes the quilisma.

I'm not sure what the rest of your server setup is, but my guess would be you are not using 5.0.1?

**Comment by olivierberten** [comment]
Finally fixed!
