### ISSUE TITLE
More recent database dump?

### ISSUE THREAD

**Issue by bacor** [gregorio-project/GregoBase#15]
The database `gregobase_online.sql` was last updated a year ago, but quite some things seem to have changed on the website since then. Would it perhaps be possible to add a more recent dump? Thanks a lot!

**Comment by olivierberten** [comment]
Time flies ;-)

Done!

**Comment by bacor** [comment]
Ah fantastic, thanks a lot! Maybe I'm missing something, but I don't yet see any new commits...?

**Comment by olivierberten** [comment]
Ouch... push had gone wrong...

Actually fixed now 😳

**Comment by Geremia** [comment]
@olivierberten I'd like a more recent dump, too, for [IsoGrego](https://isidore.co/isogrego/). Thanks.

**Comment by olivierberten** [comment]
Time keeps flying 🙄

Done!

**Comment by benyanke** [comment]
I wonder if everyone's needs might the even better served if we were able to add a simple API to the site, allowing easy fetching of data programmatically?
