### ISSUE TITLE
Add SVG output?

### ISSUE THREAD

**Issue by FGasper** [gregorio-project/GregoBase#2]
LibreOffice doesn’t print EPS currently.

SVG seems a much more versatile format.

How feasible would it be to run the PDF output through pdf2svg to get a downloadable SVG?

**Comment by olivierberten** [comment]
I'm planning to add that feature when I'm moving to v4... using MuPDF's mutools which seems more robust.

**Comment by FGasper** [comment]
On 24 Nov 2015 6:34 AM, Olivier Berten wrote:
> I'm planning to add that feature when I'm moving to v4... using MuPDF's
> mutools which seems more robust.
>

Ahh! I didn’t know of this library … good stuff.

Do you have a projected timeline for v4?

In the meantime I have conversion tools so can get by.

Thanks!

-FG

**Comment by olivierberten** [comment]
Done at last!

**Comment by FGasper** [comment]
Thank you! :-D
