### ISSUE TITLE
Mass download

### ISSUE THREAD

**Issue by igneus** [gregorio-project/GregoBase#4]
It would be great to have a possibility to download all the gabc scores contained in GregoBase (or some part of it, e.g. everything from Antiphonale Monasticum 1933 / all proper chants for Advent masses / all Kyriale chants / ...) at once, in an archive.

**Comment by olivierberten** [comment]
There's a [copy of the database](https://github.com/olivierberten/GregoBase/raw/master/gregobase_online.sql) (without history of the modifications) in this repository. I guess it would be pretty easy for you to extract whatever you need from it ;-)

If you need more, just ask.

**Comment by igneus** [comment]
Yes, I can cope with the database dump. Thanks. I just think that an export feature or from time to time released archives with exported gabc scores could be useful for other people, too. And not so many chant nerds I know are able to work with database dumps :)
